services:
  # first, we define the three mongo servers that will act as replicas
  # here, we steup the hostname ports, and startup command
  # which is the same as discussed in the previous section
  postgres-service:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 12345
    ports:
      - '5432:5432'
    networks:
      - backend_services

  redis-service:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - backend_services

networks:
  backend_services:
