name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - '!main'
      - '!production'
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          push: false
          tags: "${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:${{ github.sha }}"
          build-args: |
            NEXT_PUBLIC_EVENT_DATES=${{ vars.EVENT_DATES }}
