name: Build

on:
  workflow_dispatch:
  push:
  pull_request:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Build Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          file: Dockerfile
          push: false
          tags: "${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:${{ github.sha }}"
