name: Deploy to Staging

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged)
    runs-on: ubuntu-latest
    steps:
      - name: set environment variables
        run: |
          # DATABASE 
          echo DATABASE_URL="postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}/${{ secrets.DB_NAME_MAIN }}?schema=public" >> env

          # S3 (MinIO instance)
          echo S3_HOST="${{ secrets.S3_HOST }}" >> env
          echo S3_BUCKET="${{ secrets.S3_BUCKET_MAIN }}" >> env
          echo S3_ACS_KEY="${{ secrets.S3_ACS_KEY }}" >> env
          echo S3_ACS_SCRT="${{ secrets.S3_ACS_SCRT }}" >> env

          # AUTHENTICATION
          echo NEXTAUTH_URL="${{ secrets.NEXTAUTH_URL_STAGING }}" >> env
          echo NEXTAUTH_SECRET="${{ secrets.NEXTAUTH_SECRET }}" >> env
          
          echo GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" >> env
          echo GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" >> env

          echo FENIX_ID="${{ secrets.FENIX_ID_MAIN }}" >> env
          echo FENIX_SECRET="${{ secrets.FENIX_SECRET_MAIN }}" >> env
          echo FENIX_URL="${{ secrets.FENIX_URL_MAIN }}" >> env
          

          # Activities
          echo CALENDAR_ID="${{ secrets.CALENDAR_ID }}" >> env
          echo SCHEDULE_URL="${{ secrets.SCHEDULE_URL }}" >> env

      - name: upload env artifact
        uses: actions/upload-artifact@v3
        with:
          name: Environment
          path: env
          retention-days: 1
      - name: checkout repo
        uses: actions/checkout@v3
      - uses: tenhaus/get-release-or-tag@v2
        id: tag
      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        uses: docker/login-action@v2.1.0
        with:
          #registry: index.docker.io # optional
          username: ${{ secrets.DOCKER_USER }} # optional
          password: ${{ secrets.DOCKER_TOKEN }} # optional
          # Specifies whether the given registry is ECR (auto, true or false)
          ecr: false # optional, default is auto
          # Log out from the Docker registry at the end of a job
          logout: false # optional, default is true
      - name: Build and push Docker images
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
        uses: docker/build-push-action@v3.2.0
        with:
          file: Dockerfile
          push: true
          # List of secrets to expose to the build (e.g., key=string, GIT_AUTH_TOKEN=mytoken)
          #secrets: # optional
          # List of tags
          #"${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:${GITHUB_REF#refs/*/}"
          #"${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:latest"
          #"${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:v0.0.0"
          tags: |
            "${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:latest-main"
            "${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:${{ steps.tag.outputs.tag }}"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create ssh identity
        run: echo "${{ secrets.PRIVATE_KEY }}" > ./id_rsa
      - name: Change privateKey perms
        run: chmod 400 ./id_rsa
      - name: Download Environment
        uses: actions/download-artifact@v3
        with:
          name: Environment
      - name: copy env to destination
        run: scp -o StrictHostKeyChecking=no -i ./id_rsa ./env ubuntu@set.vps.tecnico.ulisboa.pt:~/env-main
      - name: Reload Deployment
        run: ssh -o StrictHostKeyChecking=no -i ./id_rsa ubuntu@set.vps.tecnico.ulisboa.pt sudo /home/ubuntu/deploy-main.sh ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:latest-main
